### ISSUE TITLE
** Master Task List **

### ISSUE THREAD

**Issue by akatheduelist** [Lemelisk271/welp-group-project#99]
The following requirements are necessary to pass the Group Flask Project:

- 2 full CRUD features
- 2 partial CRUD features (2-3 CRUD based on the feature) (yes, that is 4 features!)
- User Authentication (this will mostly be provided in the starter, minus a demo user)
- Landing Page (that is not a public resource page)
- Presenting your project to the rest of the cohort
- Your scorecard will have more details on the specifics. Your group will have a separate scorecard that will be connected to your personal score card (there is a Flask tab in the scorecard for your Module 5 project, that will be linked to the group scorecard and populated there)

Signup validation
dead links

Businesses

- [x] Users should be able to view all businesses. @MasoodMS95 
- [x] Users should be able to add their own business. @darocket34 
- [x] Users should be able to update their business information. @darocket34 
- [x] Users should be able to delete their business. @darocket34 

Reviews

- [x] Users should be able to view all reviews on a business.
/business/:businessId/review/all "GET"
- [x] Users should be able to add a review to a business @akatheduelist 
/business/:businessId/review "POST"
- [x] Users should be able to update their review on a business. @akatheduelist 
/review/:reviewId "PUT"
- [x] Users should be able to delete their review from a business. @akatheduelist 
/business/:businessId/review "DELETE"

Search/Filter

- [x] Users should be able to search by name, category, and or price.
- [x] Users should be able to view the results of their search.

Images

- [x] Users should be able to view all images on an associated business.
- [x] Users should be able to add an image to either their business or a business they have visited.
- [x] Users should be able to remove their images from a business.

Bonus: Google Maps API

- [ ] Users should be able to see business locations on google maps.

Bonus: Friends

- [ ] Users should be able to view their friends reviews and images.
- [ ] Users should be able to add new friends.
- [ ] Users should be able to remove friends.
